### ISSUE TITLE
picker 组件是还没有完成吗？

### ISSUE THREAD

**Issue by plylrnsdy** [allan-hx/flutter-weui#11]
1. 文档的 picker 页打不开
2. onChange 事件无效

- flutter 1.9.1+hotfix.6
- weui 0.0.5

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by allan-hx** [comment]
@plylrnsdy 不好意思, picker是还未完成的, 案例上没隐藏

**Comment by plylrnsdy** [comment]
好的
