### ISSUE TITLE
swipe和switch文档重复了

### ISSUE THREAD

**Issue by 929355193** [allan-hx/flutter-weui#16]
swipe和switch文档重复了
https://allan-hx.github.io/flutter-weui-doc/index.html#/doc/component/swipe
https://allan-hx.github.io/flutter-weui-doc/index.html#/doc/component/switch
有交流群嘛，帮忙拉一下，哈哈哈

**Comment by allan-hx** [comment]
抱歉，回复晚了，文档确实重复了，swipe组件目前处于未完成状态
