### ISSUE TITLE
文档很多组件看不到使用说明信息

### ISSUE THREAD

**Issue by 120011676** [allan-hx/flutter-weui#18]
文档很多组件看不到使用说明信息

**Comment by allan-hx** [comment]
是组件的文档打不开么？因为文档是挂在github访问不了的话需要翻墙哦！

**Comment by 120011676** [comment]
@allan-hx 
![image](https://user-images.githubusercontent.com/1992933/78752905-853ba780-79a7-11ea-9f19-e6603d21656a.png)

**Comment by allan-hx** [comment]
> @ allan-hx
> ![图片](https://user-images.githubusercontent.com/1992933/78752905-853ba780-79a7-11ea-9f19-e6603d21656a.png)
翻墙就行了
