### ISSUE TITLE
能不能做一个聊天页面

### ISSUE THREAD

**Issue by yh4922** [allan-hx/flutter-weui#3]

**Comment by allan-hx** [comment]
@yh4922 抱歉，回复晚了，什么样的聊天页面呢？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by yh4922** [comment]
@allan-hx   不是weui的  就是 类似微信聊天的 
本来我自己在写 但是那个 滚动条 和键盘那个一直没搞定
