### ISSUE TITLE
有编译警告(button/index.dart)

### ISSUE THREAD

**Issue by jonahfang** [allan-hx/flutter-weui#4]
info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
   WeButton.child, WeButton.sizeType, WeButton.theme, WeButton.size • cmps/weui/button/index.dart:13:7 • must_be_immutable

**Comment by allan-hx** [comment]
@jonahfang  抱歉, 回复晚了，现在还有这个警告么？ 怎么出现的？我这边没有看到有编译警告

**Comment by jonahfang** [comment]
使用下面的 analysis_options.yaml 设置，就能看到很多警告提示:
```
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - empty_constructor_bodies
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - slash_for_doc_comments
    - unawaited_futures
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
```

**Comment by allan-hx** [comment]
@jonahfang  抱歉，还是未能重现出来, 如果方便的话能不能把你有异常的demo发我呢？

**Comment by jonahfang** [comment]
我的开发环境：NeoVim, 用 flutter analyze --watch ：
![image](https://user-images.githubusercontent.com/16301509/54910843-1d472a00-4f28-11e9-800d-4cda85431fd5.png)


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
